# @copyright Hidden Moss
# @see Hidden Moss: https://hiddenmoss.com/
# @see repo: https://github.com/hidden-moss/xls2gd
# @author Yuancheng Zhang, https://github.com/endaye
# 
#* source file: xls_nft.xlsx
#! THIS FILE IS GENERATED BY tool_xls2gd.py.
#! DONT'T CHANGE IT MANULLY.

const music = {
	"Mute":
	{
		"id": "Mute",
		"res_bgm": "mute.ogg"
	},
	"Mozart Rondo Alla Turca 01":
	{
		"id": "Mozart Rondo Alla Turca 01",
		"res_bgm": "mozart_rondo_all_turca_sonata_chip_wave_01.ogg"
	},
	"Mozart Rondo Alla Turca 02":
	{
		"id": "Mozart Rondo Alla Turca 02",
		"res_bgm": "mozart_rondo_all_turca_sonata_chip_wave_01.ogg"
	},
	"Mozart Rondo Alla Turca 03":
	{
		"id": "Mozart Rondo Alla Turca 03",
		"res_bgm": "mozart_rondo_all_turca_sonata_chip_wave_01.ogg"
	},
	"Mozart Rondo Alla Turca 04":
	{
		"id": "Mozart Rondo Alla Turca 04",
		"res_bgm": "mozart_rondo_all_turca_sonata_xylophone_01.ogg"
	},
	"Mozart Rondo Alla Turca 05":
	{
		"id": "Mozart Rondo Alla Turca 05",
		"res_bgm": "mozart_rondo_all_turca_sonata_xylophone_01.ogg"
	},
	"Mozart Rondo Alla Turca 06":
	{
		"id": "Mozart Rondo Alla Turca 06",
		"res_bgm": "mozart_rondo_all_turca_sonata_xylophone_01.ogg"
	}
}
